name: Docker Build test

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag daphne-workshop:$(date +%s)
    - name: Run container test
      run: |
        docker run -d -p 5000:5000 --name app daphne-workshop
        sleep 3
        curl -f http://localhost:5000
