name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'
          cache: 'pip' # caching pip dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Test with pytest
        run: pytest
